### PR TITLE
Created an entry-point for rqt_topic in setup.py 

### PR DESCRIPTION
**Pull request by ahcorde**
Fixed package to run with `ros2 run rqt_topic rqt_topic`. Related to this issue https://github.com/ros-visualization/rqt_console/issues/20

Signed-off-by: ahcorde <ahcorde@gmail.com>

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Please keep the changes in a pull request focused on one semantic change described in the title. If necessary create multiple PRs for orthogonal changes.

**Comment by jacobperron** [comment]
I agree with @dirk-thomas, The fix for the connected issue is adding the entry point (and maybe the `setup.cfg` file?). The other changes to the `setup.py` are unrelated and can be done in a separate PR.

Also, please update the title to relate to the fix. `rqt_topic` is already of build type `ament_python`, so the current title is misleading.

**Comment by ahcorde** [comment]
Moved to another PR version and license changes https://github.com/ros-visualization/rqt_topic/pull/17

**Comment by jacobperron** [comment]
Please update the PR title; this package is already an ament_python package.

**Comment by wjwwood** [comment]
@jacobperron @ahcorde I'm looking to release this for the upcoming galactic fork from rolling, seems like this should get in? So friendly bump :)

**Comment by cottsay** [comment]
@ros-pull-request-builder retest this please

**Review by cottsay — APPROVED** [review]
Note that this drops the `rqt_topic` command from `/opt/ros/foo/bin`, but I think this is actually the right thing to do. A change, nonetheless.

**Pull request merged**
