### PR TITLE
Fix python3 install

### PR DESCRIPTION
**Pull request by mabelzhang**
Alternative to #35. This PR is the recommended fix and is backward-compatible with Melodic.

Because `master` branch of this repo is released to both Melodic and Noetic, we need to ensure this is backward compatible for Melodic.

I've tested in both Melodic and Noetic.

@bsb808 could you please test that this works for you and approve the PR?
Once approved, I can merge and release into Noetic. Noetic syncs about once a month, and the [last one](https://discourse.ros.org/t/preparing-for-noetic-sync-2021-11-03/22948) was Nov 4, so the next one should be in a few weeks. Once it syncs, this will be available on `apt-get`.

## To test in Noetic

Compile with installation.
Either with catkin_make (I think this is the command):
```
catkin_make install --pkg rqt_topic
```

Or with catkin-build-tools:
```
catkin config --install
catkin build rqt_topic
```

Source the local workspace
```
. install/setup.bash
```

Verify that rospack is pointing to the local workspace, as opposed to the installed binaries in `/opt/ros`:
```
$ rospack find rqt_topic
/path/to/local_ws/install/share/rqt_topic
```

Check that the installed script in `install/bin/rqt_topic` has `python3` in the shebang:
```
#!/usr/bin/python3
```

Run it:
```
roscore
rosrun rqt_topic rqt_topic
```
GUI should show up.

## To test in Melodic for backward compatibility

Compile and run as above. GUI should show up.
See that the installed script in `install/bin/rqt_topic` has `python2` in the shebang:
```
#!/usr/bin/python2
```

### CODE REVIEW

**Comment by bsb808** [comment]
I approved based on successful testing for Noetic.  I didn't verify the < Melodic behavior. 

I did notice a few differences locally from the testing instructions.  (I'm using `catkin_make`.)

1. I don't see a `install/setup.bash` file.  Perhaps referring to `devel/setup.bash`?
2. The command `rospack find rqt_topic` returns the path to source - not the installation path.  E.g., 
```
$ rospack find rqt_topic
~/catkin_ws/src/rqt_topic
```

Thank you @mabelzhang !

**Comment by mabelzhang** [comment]
Thanks! That sounds like you're in the devel space and don't have an install space. Did you issue `catkin_make install` or just `catkin_make`?

We are doing some maintainer swaps. The new maintainer might be able to approve it.

**Review by audrow — APPROVED** [review]

**Comment by mabelzhang** [comment]
Thank you @audrow for approving! I'll make the release.

**Comment by mabelzhang** [comment]
Pending approval of release PR https://github.com/ros/rosdistro/pull/31272 and the next Noetic sync, this will be on `apt-get` soon.

**Comment by mabelzhang** [comment]
@bsb808 Oh I know why, I had to run `catkin_make install` on everything to get the `install/setup.bash`. If I only ran it on one package, it didn't give it to me, heh...

**Pull request merged**
