### PR TITLE
Updated version package and license in setup.py

### PR DESCRIPTION
**Pull request by ahcorde**
Updated version package and license in setup.py

Signed-off-by: ahcorde <ahcorde@gmail.com>

### CODE REVIEW

**Comment by jacobperron** [comment]
You can target this change to `dashing-devel` directly.

**Comment by ahcorde** [comment]
Done ;)

**Comment by ahcorde** [comment]
Do we need to run CI?

**Comment by jacobperron** [comment]
> Do we need to run CI?

I think it should be okay to merge.

**Pull request merged**
